# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'askmeany' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for askmeany
	pod 'SAPlugAVPlayer'

  target 'askmeanyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'askmeanyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
